---
version: '3'
services:
  mysql:
    image: mariadb
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=foo
  todo:
    depends_on: ['mysql']
    image: foo
    ports: ['8086:8080']
    environment:
      - "DB_DSN=root:foo@tcp(mysql:3306)/mysql?charset=utf8mb4&parseTime=True&loc=Local"
